run:
  timeout: 3m

linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - goimports
    - govet
    - ineffassign
    - revive
    - staticcheck
    - unused

linters-settings:
  revive:
    confidence: 0.8

issues:
  exclude-use-default: false
  max-same-issues: 0
